In [1]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [3]:
# Creating Numpy as arrays
import numpy as np
a = np.array([1, 2, 3])
print(type(a))
print(a)


<class 'numpy.ndarray'>
[1 2 3]


In [ ]:
# 2D array
b = np.array([[1, 2, 3],[4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
# 3D array
c = np.array([[[1,2],[3, 4]],[[6,7],[8,9]]])
print(c)

[[[1 2]
  [3 4]]

 [[6 7]
  [8 9]]]


In [11]:
# you also create a array of that datatype which you like.(dtype)
np.array([1, 2, 3],dtype=float)

array([1., 2., 3.])

In [12]:
np.array([1, 2, 3],dtype=bool)

array([ True,  True,  True])

In [16]:
# np.arange
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [18]:
# with reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
# np.ones & np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# use for the initialize the array
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
# np.linspace  (linear space)
np.linspace(-10,10,10)        #(lower range, upper range, no of items that you want to generate)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [24]:
# np.random
np.random.random((3,4))

array([[0.37264676, 0.60056706, 0.91521051, 0.19571962],
       [0.85068693, 0.42712257, 0.46396736, 0.44758001],
       [0.93790811, 0.55536886, 0.2174078 , 0.57911861]])

In [25]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])