In [2]:
# array functions --> you don't need to make any function for mathematical calculation.
# also read the documentation of numpy...
import numpy as np
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[ 1., 25., 91.],
       [84., 99., 20.],
       [26., 34., 89.]])

In [ ]:
# max/min/sum/prod
# 0 --> column and 1 --> row
np.max(a1)

np.float64(99.0)

In [4]:
np.min(a1)

np.float64(1.0)

In [5]:
np.sum(a1)

np.float64(469.0)

In [6]:
np.prod(a1)

np.float64(29769267528000.0)

In [ ]:
np.max(a1,axis =0)

array([84., 99., 91.])

In [8]:
# mean/median/std/var
np.mean(a1)

np.float64(52.111111111111114)

In [9]:
np.median(a1,axis=1)

array([25., 84., 34.])

In [10]:
np.var(a1)

np.float64(1275.2098765432097)

In [11]:
# trigonometric function --> we don't use this function but see only for knowledge not use in data science.
np.sin(a1)

array([[ 0.84147098, -0.13235175,  0.10598751],
       [ 0.73319032, -0.99920683,  0.91294525],
       [ 0.76255845,  0.52908269,  0.86006941]])

In [12]:
# dot product: condition --> column no of 1st matrix = row no of 2nd matrix
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [13]:
# log and exponents
np.log(a1)

array([[0.        , 3.21887582, 4.51085951],
       [4.4308168 , 4.59511985, 2.99573227],
       [3.25809654, 3.52636052, 4.48863637]])

In [14]:
np.exp(a2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [15]:
# round/floor/ceil
np.random.random((2,3))*100  # this gives float

array([[46.41806388, 66.17427299, 81.13452308],
       [35.11328237, 34.51632795, 80.3494246 ]])

In [ ]:
# now if i want integer so i do this
np.round(np.random.random((2,3))*100)   # nearest integer pr round kar do.

array([[72., 74., 54.],
       [48.,  5., 39.]])