In [2]:
# indexing and slicing
import numpy as np
a1 = np.arange(10)   # 1D array
a2 = np.arange(12).reshape(3,4)   # 2D array
a3 = np.arange(8).reshape(2,2,2)   # 3D array
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a1[0]

np.int64(0)

In [4]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1,2]   #[row,column]

np.int64(6)

In [ ]:
a3[1,0,1]    # [in which 2D array - 1,row,column]

np.int64(5)

In [9]:
a3[0,0,0]

np.int64(0)

In [10]:
# slicing --> access multiple items at a one time
a1[2:5]    #[include:excluded]

array([2, 3, 4])

In [11]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0,:]   # produce column

array([0, 1, 2, 3])

In [ ]:
a2[2,:]   # produce column

array([ 8,  9, 10, 11])

In [16]:
a2[:,2]   # produce row

array([ 2,  6, 10])

In [17]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [19]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [38]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [43]:
a2[1,::3]

array([4, 7])

In [ ]:
a2[0:2,1::]     #[kon sa rows,kon sa column] just ask with you.

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)   # This numpy array consist of three 2-D array.
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [50]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [51]:
a3[::2]      # :: --> sabko nikal lo aur alternate ki digit likh do.

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [52]:
a3[0,1,:]        # we use (:) for getting all the value of that particular column.

array([3, 4, 5])

In [53]:
a3[1,:,1]        # [2nd 2D matrix, all rows,mid column]

array([10, 13, 16])

In [ ]:
a3[2,1:,1:]        #[3rd 2D matrix, 2nd row se end tk,2nd column se end tak]

array([[22, 23],
       [25, 26]])

In [55]:
a3[::2,0,::2]               # [alternate numpy arrays,want only 1st row,want only 1st column and 3rd column]

array([[ 0,  2],
       [18, 20]])