In [ ]:
# Iteration on numpy array  (loops in array)
import numpy as np
a1 = np.arange(11)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [8]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9
10


In [9]:
# In 2D, print a one row at one time
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [10]:
# In 3D, print a 2D array at one time
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
# how many dimension array, we use this (nditer) for accessing the each and every element
for i in np.nditer(a3):
    print(i)      # 3d --> 2D --> 1D

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
