In [1]:
# reshaping means changing the shape/dimensions of a numpy array without changing its data.
import numpy as np
arr = np.array([1,2,3,4,5,6])
new_arr = arr.reshape(2, 3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])   # original total elements = new total elements
new_arr = arr.reshape(2,2,2)
print(new_arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
# transpose: convert row into column and column into row
a2 = np.arange(12).reshape(4,3)
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [9]:
np.transpose(a2)

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [10]:
a2.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [11]:
# Ravel --> convert all dimensions of array into 1D array
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])