In [2]:
# horizontal stacking: add two or more numpy arrays in horizontal
import numpy as np
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [3]:
np.hstack((a1,a2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [4]:
np.hstack((a1,a2,a1,a2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

In [5]:
# vertical stacking
np.vstack((a1,a2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [6]:
np.vstack((a1,a2,a1,a2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
# multiple data sources ke same data ko ek sath rkhne ke liye iska use krte hai
# some data from database and some data from api and also some data from webscraping(all data similar)
# Remember one point "shape must be same "

# np.stack() --> creates a new axis, unlike vstack and hstack, stack() adds a new dimension.
a = np.array([1,2,3])
b = np.array([4,5,6])
np.stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# np.concatenate() --> joins along an existing axis
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])