In [1]:
# normal indexing and slicing
import numpy as np
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [2]:
# if we access any element so just use rom and column number
a[1,2]

np.int64(6)

In [4]:
# fancy indexing for fetch items -> accessing multiple specific position elements at a one time
import numpy as np
a = np.array([10, 20 ,30, 40, 50])
print(a[[0,2,4]])


[10 30 50]


In [7]:
# 2-D array
a2 = np.arange(12).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
# if we want 5, 2, 11
print(a2[[1,0,2],[1,2,3]])

[ 5  2 11]


In [ ]:
# why this?
# Row index         column index    element
#    1                  1             5
#    0                  2             2
#    2                  3             11
# in fancy indexing we just provide a list of index of elements.

In [15]:
# Boolean indexing
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[15, 47, 38, 71],
       [99, 19,  9, 67],
       [36, 44, 53, 44],
       [79, 74, 75, 47],
       [82, 85, 56, 80],
       [26, 82, 57, 43]], dtype=int32)

In [16]:
# find all numbers greater than 50 in array a
a > 50

array([[False, False, False,  True],
       [ True, False, False,  True],
       [False, False,  True, False],
       [ True,  True,  True, False],
       [ True,  True,  True,  True],
       [False,  True,  True, False]])

In [17]:
# if we want only those numbers which are greater tha 50
a[a > 50]

array([71, 99, 67, 53, 79, 74, 75, 82, 85, 56, 80, 82, 57], dtype=int32)

In [18]:
# find out even numbers
a % 2 == 0

array([[False, False,  True, False],
       [False, False, False, False],
       [ True,  True, False,  True],
       [False,  True, False, False],
       [ True, False,  True,  True],
       [ True,  True, False, False]])

In [19]:
a[a % 2 == 0]

array([38, 36, 44, 44, 74, 82, 56, 80, 26, 82], dtype=int32)

In [20]:
# find all numbers greater than 50 and are even
(a > 50) & (a % 2 == 0)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True, False, False],
       [ True, False,  True,  True],
       [False,  True, False, False]])

In [21]:
a[(a > 50) & (a % 2 == 0)]

array([74, 82, 56, 80, 82], dtype=int32)

In [8]:
# find all numbers that are not divisible by 7
import numpy as np
a1 = np.random.randint(100,200,24).reshape(6,4)
a1

array([[177, 190, 190, 196],
       [153, 173, 123, 113],
       [143, 149, 124, 114],
       [106, 151, 183, 124],
       [142, 113, 147, 107],
       [146, 197, 152, 183]], dtype=int32)

In [9]:
a1[a1 % 7 != 0]

array([177, 190, 190, 153, 173, 123, 113, 143, 149, 124, 114, 106, 151,
       183, 124, 142, 113, 107, 146, 197, 152, 183], dtype=int32)