In [1]:
# the term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations.
# the smaller array is "broadcast" across the larger array so that they have compatible shapes.
# same shape
import numpy as np
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
print(a)
print(b)
print(a + b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [ ]:
# different shape
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)
print(a)
print(b)
print(a + b)   # this is possible through broadcasting.

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


In [ ]:
# Broadcasting rules
# when operating on two arrays, numpy compares their shapes from right to left.
# two dimensions are compatible if --> they are equal or one of them is 1.
# if neither condition is satisfied then get "Broadcasting error"
# If dimension = 1
a = np.array([[1],[2],[3]])
b = np.array([10,20,30])
print(a + b)
# Both dimensions become compatible because one side has 1.

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
# example of incompatible shapes
# A --> (2,3)
# B --> (2,2)
# now compare from right: 3 vs 2 , so broadcasting is not possible. neither is equal nor 1.

In [6]:
# remember these rules
# --> make the two arrays have the same number of dimension.
# --> make each dimension of the two arrays the same size.
a = np.arange(12).reshape(4,3)   # 2D
b = np.arange(3)   # 1D
print(a)
print(b)
# first convert 1D array as 2D array like (1,3) then it create as (4,3), now you will be able to do arithmetic operations.
print(a + b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [8]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)
print(a)
print(b)
print(a + b)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [10]:
a = np.array([1])    # shape --> (1,1)
b = np.arange(4).reshape(2,2)   # shape --> (2,2)
print(a)
print(b)
print(a + b)

[1]
[[0 1]
 [2 3]]
[[1 2]
 [3 4]]


In [ ]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)
print(a)
print(b)
print(a + b)   # it will not work.

In [ ]:
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)
print(a)
print(b)
# both have not same shape then will not broadcast.