In [ ]:
# Working with mathematical formulas
# we know python has much more built-in function.
# now we can solve any mathematical problem by using these functions.
# sigmoid --> much more use in logistic regression and also in deep learning
#   S(x) = 1 / (1 + e^-x); formula of sigmoid
import numpy as np
def sigmoid(array):
    return 1/ (1 + np.exp(-(array)))
a = np.arange(10)
sigmoid(a)
# sigmoid lies between 0 and 1.

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661])

In [ ]:
# mean squared error  : for linear regression
actual = np.random.randint(1,50,25)
predicted = np.random.randint(1,50,25)
actual

array([31, 40, 16,  7, 27, 10, 23, 42,  3, 42,  3, 36, 45,  5, 27, 17,  9,
        6,  4, 39, 11, 31, 45, 20,  6], dtype=int32)

In [5]:
predicted

array([17, 36, 21, 41,  7, 45,  3, 27, 48, 13,  9,  1, 43, 30, 24, 10, 36,
       12, 35, 22, 42,  8, 27, 47, 19], dtype=int32)

In [ ]:
# now we calculate mean squared error on both array
actual = np.random.randint(1,50,25)
predicted = np.random.randint(1,50,25)

def mse(actual, predicted):
    return np.mean((actual - predicted)**2)

mse(actual,predicted)    # It will give the combined avg error.

np.float64(340.72)

In [ ]:
# binary cross entropy : for logistic regression
# it's a loss function which is used in binary classification problems where output is only 0 or 1.
# Generally :  lower loss = better prediction
import numpy as np
def binary_cross_entropy(actual,predicted):
    return -np.mean(actual * np.log(predicted) + (1 - actual) * np.log(1 - predicted))
actual = np.array([1,0,1,1])
predicted = np.array([0.9,0.2,0.8,0.6])

print(binary_cross_entropy(actual,predicted))

# BCE measure the quality of classification probability.

0.2656183105130591


In [ ]:
# working with missing values --> np.nan
a = np.array([1,2,3,4,5,np.nan,6])  # none and nan are not the same stuff. this nan is missing value.
a

array([ 1.,  2.,  3.,  4.,  5., nan,  6.])

In [ ]:
# how can we remove missing values
np.isnan(a)  # this tell which value is missing.

array([False, False, False, False, False,  True, False])

In [12]:
a[~np.isnan(a)]

array([1., 2., 3., 4., 5., 6.])