In [1]:
# numpy tricks(hidden power of numpy)
# np.sort() --> return a sorted copy of an array
import numpy as np
a = np.random.randint(1,100,15)
a

array([51, 17, 15, 78, 11, 97,  2, 45, 43, 61, 93,  8, 98, 18, 56],
      dtype=int32)

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[ 6, 68, 32, 84],
       [57, 76, 35, 27],
       [36, 59, 37, 68],
       [88, 15, 26, 87],
       [64, 17, 93, 31],
       [21, 86, 70, 90]], dtype=int32)

In [ ]:
#  numpy.sort(a, axis = -1,kind = none, order = none)
np.sort(a)

array([ 2,  8, 11, 15, 17, 18, 43, 45, 51, 56, 61, 78, 93, 97, 98],
      dtype=int32)

In [ ]:
np.sort(b)   # row wise sorting also use axis = 1

array([[ 6, 32, 68, 84],
       [27, 35, 57, 76],
       [36, 37, 59, 68],
       [15, 26, 87, 88],
       [17, 31, 64, 93],
       [21, 70, 86, 90]], dtype=int32)

In [5]:
np.sort(b,axis = 0)   # column wise sorting

array([[ 6, 15, 26, 27],
       [21, 17, 32, 31],
       [36, 59, 35, 68],
       [57, 68, 37, 84],
       [64, 76, 70, 87],
       [88, 86, 93, 90]], dtype=int32)

In [6]:
# for sorting in descending order
np.sort(a)[::-1]

array([98, 97, 93, 78, 61, 56, 51, 45, 43, 18, 17, 15, 11,  8,  2],
      dtype=int32)

In [8]:
# The np.append() appends values along the mentioned axis at the end of the array
a = np.random.randint(1,50,20)
a

array([35, 24, 48, 23, 14, 24, 44, 14, 29, 41, 40, 44, 20,  1, 14, 23, 27,
       28, 23, 34], dtype=int32)

In [9]:
np.append(a,200)

array([ 35,  24,  48,  23,  14,  24,  44,  14,  29,  41,  40,  44,  20,
         1,  14,  23,  27,  28,  23,  34, 200])

In [10]:
# append with 2D array
b

array([[ 6, 68, 32, 84],
       [57, 76, 35, 27],
       [36, 59, 37, 68],
       [88, 15, 26, 87],
       [64, 17, 93, 31],
       [21, 86, 70, 90]], dtype=int32)

In [13]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[ 6., 68., 32., 84.,  1.],
       [57., 76., 35., 27.,  1.],
       [36., 59., 37., 68.,  1.],
       [88., 15., 26., 87.,  1.],
       [64., 17., 93., 31.,  1.],
       [21., 86., 70., 90.,  1.]])

In [15]:
# np.concatenate() function concatenate a sequence of arrays along an existing axis.
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis = 0)   # row wise concatenate

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
np.concatenate((c,d),axis = 1)  # column wise concatenate

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [19]:
# with the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.
e = np.array([1,1,2,2,3,4,4,4,5,5,6,6])
f = np.array([[1,2,3,1],[1,2,3,2]])
print(e)
print(f)

[1 1 2 2 3 4 4 4 5 5 6 6]
[[1 2 3 1]
 [1 2 3 2]]


In [20]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [ ]:
# np.expand_dims --> we acn get the 'expanded dimensions' of an array.
# convert 1D into 2D and 2D into 3D
a    # shape --> (15,)

array([35, 24, 48, 23, 14, 24, 44, 14, 29, 41, 40, 44, 20,  1, 14, 23, 27,
       28, 23, 34], dtype=int32)

In [22]:
np.expand_dims(a,axis=0)

array([[35, 24, 48, 23, 14, 24, 44, 14, 29, 41, 40, 44, 20,  1, 14, 23,
        27, 28, 23, 34]], dtype=int32)

In [ ]:
np.expand_dims(a,axis=0).shape   # 2D array
# this is also use for making the row vector and column vector.

(1, 20)

In [26]:
# np.where() --> return the indices of elements in an input array where the given condition is satisfied.
a = np.random.randint(1,100,25)
a

array([61, 50, 26, 96, 91,  8, 16, 98,  5, 86, 24, 99, 72, 37, 17, 89, 11,
       13, 34, 66, 45, 49, 65, 29, 81], dtype=int32)

In [ ]:
# find all indices with value greater than 50
np.where(a > 50)
# it gives the index value.

(array([ 0,  3,  4,  7,  9, 11, 12, 15, 19, 22, 24]),)

In [28]:
# replace all values which is greater than 50 with zero
np.where(a > 50, 0,a)      # (a > 50, true then print 0 otherwise print a)

array([ 0, 50, 26,  0,  0,  8, 16,  0,  5,  0, 24,  0,  0, 37, 17,  0, 11,
       13, 34,  0, 45, 49,  0, 29,  0], dtype=int32)

In [29]:
# replace all even values with zero
np.where(a % 2 == 0,0,a)

array([61,  0,  0,  0, 91,  0,  0,  0,  5,  0,  0, 99,  0, 37, 17, 89, 11,
       13,  0,  0, 45, 49, 65, 29, 81], dtype=int32)

In [30]:
# np.argmax() --> return indices of the max element of the array in a particular axis.
a

array([61, 50, 26, 96, 91,  8, 16, 98,  5, 86, 24, 99, 72, 37, 17, 89, 11,
       13, 34, 66, 45, 49, 65, 29, 81], dtype=int32)

In [31]:
np.argmax(a)

np.int64(11)

In [32]:
# 2D me also this work for row or column.
b

array([[ 6, 68, 32, 84],
       [57, 76, 35, 27],
       [36, 59, 37, 68],
       [88, 15, 26, 87],
       [64, 17, 93, 31],
       [21, 86, 70, 90]], dtype=int32)

In [ ]:
np.argmax(b,axis = 0)   # column wise

array([3, 5, 4, 5])

In [ ]:
np.argmax(b,axis = 1)   # row wise

array([3, 1, 3, 0, 2, 3])

In [35]:
# np.argmin() --> indices of lower number
np.argmin(a)

np.int64(8)

In [36]:
# np.cumsum --> it is used when we want to compute the cumulative sum of arrays over a given axis.
a

array([61, 50, 26, 96, 91,  8, 16, 98,  5, 86, 24, 99, 72, 37, 17, 89, 11,
       13, 34, 66, 45, 49, 65, 29, 81], dtype=int32)

In [37]:
np.cumsum(a)

array([  61,  111,  137,  233,  324,  332,  348,  446,  451,  537,  561,
        660,  732,  769,  786,  875,  886,  899,  933,  999, 1044, 1093,
       1158, 1187, 1268])

In [38]:
b

array([[ 6, 68, 32, 84],
       [57, 76, 35, 27],
       [36, 59, 37, 68],
       [88, 15, 26, 87],
       [64, 17, 93, 31],
       [21, 86, 70, 90]], dtype=int32)

In [39]:
np.cumsum(b)   # first convert into 1D then produce cumulative sum

array([   6,   74,  106,  190,  247,  323,  358,  385,  421,  480,  517,
        585,  673,  688,  714,  801,  865,  882,  975, 1006, 1027, 1113,
       1183, 1273])

In [40]:
np.cumsum(b,axis=0)   # column wise

array([[  6,  68,  32,  84],
       [ 63, 144,  67, 111],
       [ 99, 203, 104, 179],
       [187, 218, 130, 266],
       [251, 235, 223, 297],
       [272, 321, 293, 387]])

In [41]:
np.cumsum(b,axis=1)   # row wise

array([[  6,  74, 106, 190],
       [ 57, 133, 168, 195],
       [ 36,  95, 132, 200],
       [ 88, 103, 129, 216],
       [ 64,  81, 174, 205],
       [ 21, 107, 177, 267]])

In [42]:
# np.cumprod() --> find the product of all corresponding elements
np.cumprod(a)

array([                  61,                 3050,                79300,
                    7612800,            692764800,           5542118400,
                88673894400,        8690041651200,       43450208256000,
           3736717910016000,    89681229840384000,  8878441754198016000,
       -6388236277577154560,  3442930687869452288,  3189589472652034048,
        7172301960387756032,  5108345269427109888, -7378487792285777920,
        7385832094217273344,  7849572301891698688,  2742616184644960256,
        5260984531636191232, -8524142844129050624, -7392469521518297088,
       -8494220884276412416])

In [43]:
# np.percentile() --> it is used to compute the nth percentile of the given data (array elements) along the specified axis.
a

array([61, 50, 26, 96, 91,  8, 16, 98,  5, 86, 24, 99, 72, 37, 17, 89, 11,
       13, 34, 66, 45, 49, 65, 29, 81], dtype=int32)

In [ ]:
np.percentile(a,100)    # give largest value

np.float64(99.0)

In [45]:
np.percentile(a,0)   # give smaller value

np.float64(5.0)

In [46]:
np.percentile(a,50)   # median value

np.float64(49.0)

In [47]:
np.median(a)

np.float64(49.0)

In [48]:
# np.histogram() --> which represent the frequency of data distribution in the graphical form.
a

array([61, 50, 26, 96, 91,  8, 16, 98,  5, 86, 24, 99, 72, 37, 17, 89, 11,
       13, 34, 66, 45, 49, 65, 29, 81], dtype=int32)

In [49]:
np.histogram(a,bins=[0,50,100])

(array([13, 12]), array([  0,  50, 100]))

In [51]:
# np.corrcoef() --> return pearson product moment correlation co-efficient.
# correlation is show only in between -1 to 1.
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [52]:
# np.isin() --> with the help of this, we can see that one array having values are checked in a different numpy array having diff elements with diff sizes.
a

array([61, 50, 26, 96, 91,  8, 16, 98,  5, 86, 24, 99, 72, 37, 17, 89, 11,
       13, 34, 66, 45, 49, 65, 29, 81], dtype=int32)

In [54]:
items = [10,20,30,40,50,60,70,80,90,100]
np.isin(a,items)

array([False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [55]:
# np.flip() --> it reverse the order of array elements along the specified axis, preserving the shape of the array.
a

array([61, 50, 26, 96, 91,  8, 16, 98,  5, 86, 24, 99, 72, 37, 17, 89, 11,
       13, 34, 66, 45, 49, 65, 29, 81], dtype=int32)

In [ ]:
np.flip(a)   # mirror image

array([81, 29, 65, 49, 45, 66, 34, 13, 11, 89, 17, 37, 72, 99, 24, 86,  5,
       98, 16,  8, 91, 96, 26, 50, 61], dtype=int32)

In [57]:
b

array([[ 6, 68, 32, 84],
       [57, 76, 35, 27],
       [36, 59, 37, 68],
       [88, 15, 26, 87],
       [64, 17, 93, 31],
       [21, 86, 70, 90]], dtype=int32)

In [ ]:
np.flip(b)    # column flip then also row flip
# for flip column --> axis = 0
# for flip row --> axis = 1

array([[90, 70, 86, 21],
       [31, 93, 17, 64],
       [87, 26, 15, 88],
       [68, 37, 59, 36],
       [27, 35, 76, 57],
       [84, 32, 68,  6]], dtype=int32)

In [59]:
# np.put() --> replaces specific elements of an array with given values of p_array. array indexed works on flattened array.
a

array([61, 50, 26, 96, 91,  8, 16, 98,  5, 86, 24, 99, 72, 37, 17, 89, 11,
       13, 34, 66, 45, 49, 65, 29, 81], dtype=int32)

In [61]:
np.put(a,[0,1],[110,530])    # it will do permanent changes.then we print again this a.
a

array([110, 530,  26,  96,  91,   8,  16,  98,   5,  86,  24,  99,  72,
        37,  17,  89,  11,  13,  34,  66,  45,  49,  65,  29,  81],
      dtype=int32)

In [62]:
# np.delete() --> return the new array with the deletion sub arrays along with the mentioned axis.
# numpy.delete(arr,obj,axis = none)
a

array([110, 530,  26,  96,  91,   8,  16,  98,   5,  86,  24,  99,  72,
        37,  17,  89,  11,  13,  34,  66,  45,  49,  65,  29,  81],
      dtype=int32)

In [ ]:
np.delete(a,0)  # delete single item

array([530,  26,  96,  91,   8,  16,  98,   5,  86,  24,  99,  72,  37,
        17,  89,  11,  13,  34,  66,  45,  49,  65,  29,  81], dtype=int32)

In [65]:
# delete multiple items
np.delete(a,[0,2,4])

array([530,  96,   8,  16,  98,   5,  86,  24,  99,  72,  37,  17,  89,
        11,  13,  34,  66,  45,  49,  65,  29,  81], dtype=int32)