In [1]:
# set functions
import numpy as np
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [2]:
np.intersect1d(m,n)

array([3, 4, 5])

In [4]:
np.setdiff1d(m,n)

array([1, 2])

In [6]:
np.setdiff1d(n,m)

array([6, 7])

In [7]:
np.setxor1d(m,n)   # remove common values which are present in both


array([1, 2, 6, 7])

In [11]:
# np.in1d(m,1)   # like a membership operator
# this function is remove from numpy 2.0
# so we use np.in1d() in place of np.isin()
import numpy as np
m = np.array([1,2,3,4,5])
n = np.array([2,4,6])

print(np.isin(m,n))

[False  True False  True False]


In [12]:
# np.setxor1d() --> remove common values which are present in both.
np.setxor1d(m,n)


array([1, 3, 5, 6])

In [15]:
# np.in1d() --> for search any value in a given array in the boolean form
#  np.in1d()  # this was remove from the numpy 2.0
# so we use np.isin()

a = np.array([1,2,3,4,5,6])
b = np.array([2,4,6])

print(np.isin(a, b))

[False  True False  True False  True]


In [16]:
# np.clip() --> it is used to clip(limit) the values in an array
a

array([1, 2, 3, 4, 5, 6])

In [17]:
np.clip(a,a_min=2,a_max=4)

array([2, 2, 3, 4, 4, 4])